//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdeabizDemo.IdeabizHandler {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Ideabiz : global::System.Configuration.ApplicationSettingsBase {
        
        private static Ideabiz defaultInstance = ((Ideabiz)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Ideabiz())));
        
        public static Ideabiz Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CONSUMER_KEY {
            get {
                return ((string)(this["CONSUMER_KEY"]));
            }
            set {
                this["CONSUMER_KEY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CONSUMER_SECRET {
            get {
                return ((string)(this["CONSUMER_SECRET"]));
            }
            set {
                this["CONSUMER_SECRET"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ACCESS_TOKEN {
            get {
                return ((string)(this["ACCESS_TOKEN"]));
            }
            set {
                this["ACCESS_TOKEN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string REFRESH_TOKEN {
            get {
                return ((string)(this["REFRESH_TOKEN"]));
            }
            set {
                this["REFRESH_TOKEN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ideabiz.lk/apicall/token")]
        public string TOKEN_API {
            get {
                return ((string)(this["TOKEN_API"]));
            }
            set {
                this["TOKEN_API"] = value;
            }
        }
    }
}
